services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitnet

  scada-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scada-producer
    env_file: ../.env
    command: ["python", "producer.py"]
    depends_on:
      - rabbitmq
    networks:
      - rabbitnet

networks:
  rabbitnet:
    driver: bridge