services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
    networks:
      - rabbitnet
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  setup-rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq-setup
    env_file: ../../.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitnet

networks:
  rabbitnet:
    driver: bridge